from odoo.odoo import odoo_connect
from odoo.odoo import odoo_sys_uno
from odoo.odoo import odoo_sys_dos
from odoo.odoo import odoo_sys_tres
from odoo.odoo import odoo_sys_cuatro
from odoo.odoo import odoo_sys_cinco
from odoo.odoo import odoo_sys_seis
from odoo.odoo import odoo_sys_siete
from odoo.odoo import odoo_sys_ocho
from odoo.odoo import odoo_sys_nueve
from odoo.odoo import odoo_sys_diez
from odoo.odoo import odoo_sys_once
from odoo.odoo import odoo_sys_doce
from odoo.odoo import odoo_sys_trece
from odoo.odoo import odoo_sys_catorce
from odoo.odoo import odoo_sys_quince
from odoo.odoo import odoo_sys_dieciseis
from odoo.odoo import odoo_sys_diecisiete
from odoo.odoo import odoo_sys_dieciocho
from odoo.odoo import odoo_sys_diecinueve
from odoo.odoo import odoo_sys_veinte
from odoo.odoo import odoo_sys_veintiuno
from odoo.odoo import odoo_sys_veintidos
from odoo.odoo import odoo_sys_veintitres

from odoo.odoo import odoo_ct_uno
from odoo.odoo import odoo_ct_dos
from odoo.odoo import odoo_ct_tres
from odoo.odoo import odoo_ct_cuatro
from odoo.odoo import odoo_ct_cinco

from odoo.odoo import odoo_tec_uno
from odoo.odoo import odoo_tec_dos
from odoo.odoo import odoo_tec_tres
from odoo.odoo import odoo_tec_cuatro
from odoo.odoo import odoo_tec_cinco
